---
#- hosts: research_environment
- hosts: analytics_terminal7
  become: yes
  become_method: sudo

  vars:
    custom_repo: true
    deploy_iptables: true
    install_r_packages: true
    update_rstudio: true
    envir: prod

# vars_files:
#   - ~/RHACCOUNT

  pre_tasks:
    - name: register RHEL7 repo
      command: "/usr/bin/subscription-manager repos --enable=rhel-7-server-rpms --enable=rhel-7-server-extras-rpms --enable=rhel-7-server-optional-rpms"
    - name: register RHEL7 RHSCL Repo
      shell: "/usr/bin/subscription-manager repos --enable=rhel-server-rhscl-7-rpms"
    - name: register RHEL7 DevTools
      shell: "/usr/bin/subscription-manager repos --enable=rhel-7-server-devtools-rpms"
    - name: register RHEL7 DevTools
      shell: "/usr/bin/subscription-manager repos --enable=rhel-server-rhscl-7-rpms"
    - name: list RHEL enabled repos
      shell: "/usr/bin/subscription-manager repos --list-enabled"
      register: enabled_repos
    - debug:
        msg: "RHEL Enabled Repos: {{ enabled_repos }}"
  tasks:
    - name: Install Development Tools
#     shell:  yum groupinstall "Development Tools" -y
      yum:
        name: "@Development tools"
        state: present

    - name: Install R Udunits Dependencies
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - udunits2
        - udunits2-devel

    - name: Update R Devtools
      command: /usr/bin/Rscript --slave --no-save --no-restore-history -e "if (! ('{{ item }}' %in% installed.packages()[,'Package'])) { install.packages(pkgs='{{ item }}', INSTALL_opts=c('--no-test-load'),repos=c('http://cran.rstudio.com/'),dep=TRUE); print('Added'); } else { print('Already installed'); }"
      with_items:
        - sf
        - units
        - devtools
      register: r_result
      failed_when: "r_result.rc != 0 or 'had non-zero exit status' in r_result.stderr"
      changed_when: "'Added' in r_result.stdout"
#      environment: "{{ r_env_vars }}"
      tags:
        - r Devtools    
#   - name: Install JAVA OpenJDK 1.8
#     shell: yum install java-1.8.0-openjdk java-1.8.0-openjdk-devel -y

# roles:
#   - {role: puppet_disable, when: "disable_puppet"}
#   - {role: iptables, when: "iptables_config"}
#    - {role: common, when: "install_glusterfs"}

#- include: deploy_development_terminalRH7.yml
#- include: deploy_r_terminalRH7.yml

#- hosts: analytics_terminal7
#- hosts: research_environment
#  become: yes
#  become_method: sudo
  roles:
#   - {role: eod, when: "install_desktop"}
#   - {role: log-courier, when: "install_logstash"}
##  - r_RH7
##  - r-studio-serverRH7
##  - r-studio-server-configRH7
##  - r-shinyRH7
##  - r-shiny-configRH7
##  - r-studio-desktopRH7
##  - eod7
##  - odbc7
##  - python27RH7-System
##  - postgresql-client7
### - python-libs

  post_tasks:
    - name: Open port range for app prototyping
      command: "iptables -I {{ iptables_chain }} 3 -m state --state NEW -p tcp --dport 8000:8100 -s {{ hostvars[item]['ansible_ssh_host'] }} -j ACCEPT"
      when: iptables_config
      with_items: "{{ groups['proxy_server'] }}"

    - name: Save rules
      command: "/sbin/service iptables save"
      when: iptables_config

##########################################################  Python Package Updates ##############################################################
### - name: Install Python dep packages
#   - name: SCL Enable Pip Install 
#     shell: |
#       scl enable python27 -- pip install "{{ python_dep_packages_mod }}" 
#     become: yes
#     become_method: sudo
###   pip:
###     name: "{{ python_dep_packages_mod }}"
###     state: present
###     executable: /usr/local/bin/pip
##      executable: /opt/rh/python27/root/usr/bin/pip
##       executable: "{{ python_pip_bin }}"
#    # when: install_python
#      tags:
#        - python-libs
#        - python2-libs
 
### - name: Install Python packages for 27
###   pip:
###     name: "{{ python_packages }}"
###     state: present
###     executable: /usr/local/bin/pip
##      executable: /opt/rh/python27/root/usr/bin/pip
##      executable: "{{ python_pip_bin }}"
#   # when: install_python
#     tags:
#       - python-libs
#       - python2-libs
#
    - name: Install Python packages for 36
      pip:
        name: "{{ item }}"
#       name: "{{ python3_packages }}"
        state: present
        executable: /usr/bin/pip3
##      executable: "{{ python3_pip_bin }}"
#   # when: install_python
#     tags:
#       - python-libs
#       - python3-libsp
      with_items:
        - ['Cython','beaker','cairocffi','Canvas','cracklib','pcrypto','pycurl','dateutils','pydbus','decorator','egg','flock','folium','pkgconfig','iniparse','ipython','xmpppy']
# Remove pycups
#       - ['Cython','beaker','cairocffi','Canvas','cracklib','pcrypto','pycups','pycurl','dateutils','pydbus','decorator','egg','flock','folium','pkgconfig','iniparse','ipython','xmpppy']
        - ['jinja2','lxml','orca','ORBit','paramiko','pydocs','pyodbc','pysolr','pytz','pyzmq','readline','python-space','pyinsane','numpy','scipy','scikit-learn','slip','svn','theano',]
        - ['tornado','vincent','pyaml','cookiecutter','luigi','statsmodels','keras']
#      loop:
#        - Cython
#        - beaker
#        - cairocffi
#        - Canvas
#        - cracklib
#        - pycrypto
#        - pycups
#        - pycurl
#        - dateutils
#        - pydbus
#        - decorator
#        - egg
#        - flock
#        - folium
#        - pkgconfig
#        - iniparse
#        - ipython
#        - xmpppy
#        - jinja2
#        - lxml
#        - orca
#        - ORBit
#        - paramiko
#        - pydocs
#        - pyodbc
#        - pysolr
#        - pytz
#        - pyzmq
#        - readline
#        - python-space
#        - pyinsane
#        - numpy
#        - scipy
#        - scikit-learn
#        - slip
#        - svn
#        - theano
#        - tornado
#        - vincent
#        - pyaml
#        - cookiecutter
#        - luigi
#        - statsmodels
#        - keras 
 
##########################################################  Python Package Updates ##############################################################

##########################################################  R-Package Updates ##############################################################

#   - name: Install R packages 1
#     command: /usr/bin/Rscript --slave --no-save --no-restore-history -e "if (! ('{{ item }}' %in% installed.packages()[,'Package'])) { install.packages(pkgs='{{ item }}', INSTALL_opts=c('--no-test-load'),repos=c('http://cran.rstudio.com/'),dep=TRUE); print('Added'); } else { print('Already installed'); }"
#     with_items: "{{ r_packages }}"
#     register: r_result
#     failed_when: "r_result.rc != 0 or 'had non-zero exit status' in r_result.stderr"
#     changed_when: "'Added' in r_result.stdout"
    
#   - name: Install R packages with opts
    # vars:
    #   do_r_install_w_opts: False
#     command: /usr/bin/Rscript --slave --no-save --no-restore-history -e "if (! ('{{ item.name }}' %in% installed.packages()[,'Package'])) { install.packages(pkgs='{{ item.name }}', configure.args='--with-{{ item.name }}-lib={{ item.lib }}, --with-{{ item.name }}-include={{ item.include}}', INSTALL_opts=c('--no-test-load'),repos=c('http://cran.rstudio.com/'),dep=TRUE); print('Added'); } else { print('Already installed'); }"
#     with_items: "{{ r_packages_with_opts }}"
#     register: r_result
#     failed_when: "r_result.rc != 0 or 'had non-zero exit status' in r_result.stderr"
#     changed_when: "'Added' in r_result.stdout"
    # environment: "{{ r_env_vars }}"
    # tags:
    #   - r
    # when: install_r_packages and do_r_install_w_opts
    
#   - name: Fix libcurl error
#     yum:
#       name: libcurl-devel
#       state: present
    # tags:
    #   - r
    
#   - name: Install R packages from Github
    # vars:
    #   do_r_install_github: False
#     command: /usr/bin/Rscript --slave --no-save --no-restore-history -e "if (! ('{{ item.name }}' %in% installed.packages()[,'Package'])) { install.packages(pkgs='{{ item.name }}', repos=c('http://cran.rstudio.com/')); print('Added'); } else { print('Already installed'); }"
    # command: /usr/bin/Rscript --slave --no-save --no-restore-history -e "library(devtools); if (! ('{{ item.name }}' %in% installed.packages()[,'Package'])) { install_github('{{ item.user }}/{{ item.name }}'); print('Added'); } else { print('Already installed'); }"
#     with_items: "{{ r_packages_github }}"
#     register: r_github_result
#     failed_when: "r_github_result.rc != 0 or 'had non-zero exit status' in r_github_result.stderr"
#     changed_when: "'Added' in r_github_result.stdout"
    # environment: "{{ r_env_vars }}"
    # tags:
    #   - r
    # when: install_r_packages and do_r_install_github

##########################################################  R-Package Updates ###################################################################

