---
- hosts: analytics_terminal7
  #- hosts: analytics_terminal
  become: yes
  become_method: sudo

  roles:
#     - {role: epel, when: "use_epel and not 'production' in group_names"}
##    - {role: epel7, when: "use_epel and not 'production' in group_names"}
##    - {role: pyenvRH7, when: "install_python and custom_repo"}
##    - {role: python2RH7, when: "install_python and custom_repo"}
##    - {role: python3RH7, when: "install_python and custom_repo"}
#     - {role: python, when: "install_python and custom_repo"}
#     - {role: python-build, when: "not custom_repo"}
#     - {role: python3, when: "install_python and custom_repo"}
#     - {role: python3-build, when: "not custom_repo"}
#     - devtools
#     - devtools6
##    - devtools7
##    - ruby
#     - jdk
##    - openjdk1.8
##    - pycharmRH7
#     - pycharm
#     - postgresql-client
##    - postgresql-client7
###   - nginxRH7
#     - spark
###   - spark3
#     - sublime
###   - sublime3
#     - nodejs
###   - nodejs10
###   - redis
###   - maven
###   - intellij
##    - clouseau
#     - odbc
      - odbc7
      - python-libs
      # - julia

# Install development packages
- hosts: analytics_terminal
  become: yes
  tasks:
    - name: Install development packages
      yum:
        name: "{{ item }}"
        state: present
        disable_gpg_check: yes
      with_items:
        - "@development"
        - gcc-gfortran
        - python-devel

    - name: Install custom RPMs
      yum:
        name: "{{ item }}"
        state: present
        disable_gpg_check: yes
      with_items:
        - xsv
        - gnucobol
        - htop
        - p7zip
        - rhobot
      when: custom_repo
